In [ ]:
#　画像の微分　　隣のピクセルの画素との変化量

In [ ]:
# エッジの検出（Sobel・Laplacian） LaplacianGaush

In [4]:
import cv2

In [2]:
img = cv2.imread('src/Lena.jpg', 0)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [6]:
# sobel
# x方向微分
img_sobelx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=3)
# y方向微分
img_sobely = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=3)

In [7]:
img_sobelx

array([[   0.,   -4.,   -6., ...,  -72., -174.,    0.],
       [   0.,   -1.,   -5., ...,  -68., -176.,    0.],
       [   0.,    3.,   -5., ...,  -58., -169.,    0.],
       ...,
       [   0.,   31.,   14., ...,   -1.,  -12.,    0.],
       [   0.,   51.,   26., ...,    6.,    9.,    0.],
       [   0.,   58.,   28., ...,   10.,   20.,    0.]], dtype=float32)

In [8]:
# 微分したものはマイナスが入っているので、0-255段階に直す
img_sobelx = cv2.convertScaleAbs(img_sobelx)
img_sobely = cv2.convertScaleAbs(img_sobely)

In [5]:
img_sobelx

array([[  0,   4,   6, ...,  72, 174,   0],
       [  0,   1,   5, ...,  68, 176,   0],
       [  0,   3,   5, ...,  58, 169,   0],
       ...,
       [  0,  31,  14, ...,   1,  12,   0],
       [  0,  51,  26, ...,   6,   9,   0],
       [  0,  58,  28, ...,  10,  20,   0]], dtype=uint8)

In [9]:
cv2.imshow('x', img_sobelx)
cv2.imshow('y', img_sobely)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [10]:
# laplacian filter

In [12]:
# 方向がないため入力画像とビット深度のみでいい
img_lap = cv2.Laplacian(img, cv2.CV_32F)

In [13]:
img_lap = cv2.convertScaleAbs(img_lap)

In [15]:
# 二次の微分のため値が弱い　ー＞はっきりさせるため
# しかしノイズが発生するー＞ガウスを用いてノイズ除去
img_lap *= 2
cv2.imshow('img_lap', img_lap)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# Laplacian Of Gaussian Filter

In [16]:
img_blur = cv2.GaussianBlur(img, (3,3), 2)
img_lap2 = cv2.Laplacian(img_blur, cv2.CV_32F)
img_lap2 = cv2.convertScaleAbs(img_lap2)

In [18]:
img_lap2 *= 2
cv2.imshow('img_lap2', img_lap2)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# エッジの検出（Canny）
"""
Cannyのアルゴリズム
①ガウシアンフィルタでぼかす（ノイズ除去）
②Sobelフィルターで微分する（x、yそれぞれ取得　　画素値の2乗和をスクエアルートで）
③極大点を探す（グラデーションなどを除去）
④2段階の閾値処理でエッジを残す（エッジ->画素値の変化が大きいところ）
"""

In [19]:
import cv2

In [20]:
img = cv2.imread('src/Lena.jpg', 0)

In [21]:
# 第2、第3の二つの閾値をうまく調整することによってより良い画像にする
img_canny = cv2.Canny(img, 100, 200)
cv2.imshow('img_canny', img_canny)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [24]:
# 直線の検出
"""
①画素のある点を探す
②θを様々な値に設定しρを計算
③全ての点で①と②を繰り返す
④ρとθの出現頻度を集計
⑤出現頻度が最も多いものもしくは閾値より大きいものが直線
"""

'\n①画素のある点を探す\n②θを様々な値に設定しρを計算\n③全ての点で①と②を繰り返す\n④ρとθの出現頻度を集計\n⑤出現頻度が最も多いものもしくは閾値より大きいものが直線\n'

In [37]:
import cv2
import numpy as np

In [26]:
img = cv2.imread('src/road.jpg')
img_g = cv2.imread('src/road.jpg', 0)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [27]:
img_canny = cv2.Canny(img_g, 300, 450)
cv2.imshow('img_canny', img_canny)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [28]:
# 第1：入力画像、第2：ρの刻み値、第3：θの刻み値、第4：組み合わせが100回以上あったら蓄えられる
lines = cv2.HoughLines(img_canny, 1, np.pi/100, 100)

In [29]:
lines

array([[[875.       ,   1.5707964]],

       [[453.       ,   1.5393804]],

       [[604.       ,   0.       ]],

       [[793.       ,   1.6022123]],

       [[829.       ,   1.5707964]],

       [[847.       ,   1.5393804]],

       [[826.       ,   1.5707964]],

       [[622.       ,   1.1938052]],

       [[444.       ,   1.5707964]],

       [[846.       ,   1.6022123]],

       [[776.       ,   1.6336282]],

       [[876.       ,   1.5079646]],

       [[448.       ,   1.5393804]],

       [[845.       ,   1.5707964]],

       [[863.       ,   1.5707964]],

       [[858.       ,   1.5393804]],

       [[867.       ,   1.5393804]],

       [[437.       ,   1.5707964]],

       [[790.       ,   1.6336282]],

       [[812.       ,   1.6336282]]], dtype=float32)

In [30]:
for i in lines[:]:
    rho = i[0][0]
    theta = i[0][1]
    a = np.cos(theta)
    b = np.sin(theta)
    # 原点からρの値の座標
    x0 = rho * a
    y0 = rho * b
    # 始点
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    # 終点
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(img, (x1,y1), (x2,y2), (255,0,0), 1)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [2]:
# 円の検出

In [17]:
img2 = cv2.imread('src/grapes.jpg')
img2_g = cv2.imread('src/grapes.jpg', 0)
cv2.imshow('img', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [8]:
# 引数が何か見ることができる
circles = cv2.HoughCircles?

Docstring:
HoughCircles(image, method, dp, minDist[, circles[, param1[, param2[, minRadius[, maxRadius]]]]]) -> circles
.   @brief Finds circles in a grayscale image using the Hough transform.
.   
.   The function finds circles in a grayscale image using a modification of the Hough transform.
.   
.   Example: :
.   @include snippets/imgproc_HoughLinesCircles.cpp
.   
.   @note Usually the function detects the centers of circles well. However, it may fail to find correct
.   radii. You can assist to the function by specifying the radius range ( minRadius and maxRadius ) if
.   you know it. Or, in the case of #HOUGH_GRADIENT method you may set maxRadius to a negative number
.   to return centers only without radius search, and find the correct radius using an additional procedure.
.   
.   It also helps to smooth image a bit unless it's already soft. For example,
.   GaussianBlur() with 7x7 kernel and 1.5x1.5 sigma or similar blurring may help.
.   
.   @param image 8-bit, single-chann

In [25]:
circles = cv2.HoughCircles(img2_g, cv2.HOUGH_GRADIENT, dp=1, minDist=1, param1=20, param2=35, minRadius=1, maxRadius=30)

In [38]:
circles = np.uint16(np.around(circles))

In [39]:
for i in circles[0]:
    cv2.circle(img2, (i[0],i[1]), i[2], (255,0,0), 1)
cv2.imshow('img', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# モルフォルジー演算

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("src/floor.jpg",0)

In [3]:
ret, img_th = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY)
cv2.imshow("img",img_th)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [6]:
kernel = np.ones((3,3), dtype=np.uint8)
img_d = cv2.dilate(img_th, kernel)
img_e = cv2.erode(img_th, kernel)

In [8]:
cv2.imshow("img",img_th)
cv2.imshow("e", img_e)
cv2.imshow("d", img_d)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [8]:
img_c = cv2.morphologyEx(img_th, cv2.MORPH_CLOSE, kernel)

In [9]:
cv2.imshow("c",img_c)
cv2.imshow("d", img_d)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# インペイント・・・落書きを消すなど

In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("src/Bus.jpg")
img_mask = cv2.imread("src/Mask.jpg",0)

In [3]:
cv2.imshow("Mask",img_mask)
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [5]:
thresh = 1
ret, img_bin = cv2.threshold(img_mask, thresh, 255, cv2.THRESH_BINARY)
cv2.imshow("img", img_bin)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [6]:
img_dst = cv2.inpaint(img, img_bin, 3, cv2.INPAINT_NS)
cv2.imshow("img",img)
cv2.imshow("inpaint",img_dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
# 特別抽出

In [ ]:
import cv2
import numpy as np
import copy

In [ ]:
img = cv2.imread("src/buildings.jpg")
img_g = cv2.imread("src/buildings.jpg",0)

In [ ]:
img_harris = copy.deepcopy(img)
img_dst = cv2.cornerHarris(img_g, 2, 3, 0.04)